# Generated by Django 4.0.3 on 2022-04-19 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0004_alter_blogentry_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Musicy.author'),
        ),
    ]
