# Generated by Django 4.0.3 on 2022-04-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0007_alter_blogentry_autor_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='autor',
        ),
    ]
