# Generated by Django 4.0.3 on 2022-04-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0009_blogentry_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogentry',
            old_name='created_by',
            new_name='autor',
        ),
    ]
