# Generated by Django 4.0.3 on 2022-04-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0012_alter_blogentry_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
    ]
