# Generated by Django 4.0.3 on 2022-04-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0013_alter_blogentry_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
