# Generated by Django 4.0.3 on 2022-04-27 19:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0019_rename_musico_pic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
