# Generated by Django 4.0.3 on 2022-04-27 20:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0020_alter_blogentry_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='imagen',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
    ]
