# Generated by Django 4.0.3 on 2022-04-27 20:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0021_blogentry_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='imagen',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
