# Generated by Django 4.0.3 on 2022-05-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Blog.blogentry')),
            ],
        ),
    ]
