# Generated by Django 4.0.3 on 2022-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.DeleteModel(
            name='BlogPicture',
        ),
    ]
