# Generated by Django 4.0.3 on 2022-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0003_rename_musicians_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tono',
            field=models.CharField(default='x', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='acordes',
            field=models.CharField(max_length=200),
        ),
    ]
