# Generated by Django 4.0.3 on 2022-04-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0010_rename_created_by_blogentry_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/<id>'),
        ),
    ]
