# Generated by Django 4.0.3 on 2022-04-19 01:11

import Musicy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0011_alter_blogentry_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
