# Generated by Django 4.0.3 on 2022-04-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicy', '0022_alter_blogentry_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='imagen',
        ),
    ]
